# Generated by Django 4.2.16 on 2024-10-10 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_blogpost_userposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.IntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=600)),
                ('date_cmnt_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
