# Generated by Django 4.2.16 on 2024-10-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
