# Generated by Django 4.2.16 on 2024-10-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_blogcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='postedby_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
