# Generated by Django 4.2.16 on 2024-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_blogcomment_postedby_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
