# Generated by Django 4.2.16 on 2024-10-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_blogcomment_firstname_blogcomment_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('adminname', models.CharField(max_length=100, null=True)),
                ('blocked_status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
